name: CI
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        # Required mail server address if not connection_url:
        connection_url: smtp://${{secrets.MAIL_ADDRESS}}:${{secrets.MAIL_PASSWORD}}@smtp.gmail.com:587 
        server_address: smtp.gmail.com
        secure: true
        subject: Github Actions job result
        # Required recipients' addresses:
        to: enzo_17_05@hotmail.com
        # Required sender full name (address can be skipped):
        from: Enzo Skywalker # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low
        # Optional nodemailerlog: true/false
        nodemailerlog: true
        # Optional nodemailerdebug: true/false if true lognodem will also be set true
        nodemailerdebug: true
