name: CI
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: hotmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: sender@example.com
          to-email: enzo_kpo_01@hotmail.com
          username: ${{secrets.MAIL_ADDRESS}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
