name: CI
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: dawidd6/action-send-mail@v3
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        # Required mail server address if not connection_url:
        connection_url: smtp://${{secrets.MAIL_ADDRESS}}:${{secrets.MAIL_PASSWORD}}@server:465 
        server_address: smtp.gmail.com
        # Server 465, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_ADDRESS}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: enzofriasborda@gmail.com
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low
        # Optional nodemailerlog: true/false
        nodemailerlog: true
        # Optional nodemailerdebug: true/false if true lognodem will also be set true
        nodemailerdebug: true

    # - name: Send email
    #   uses: devellany/send-mail@v1.0.2
    #   with:
    #        host: smtp.google.com
    #        account: enzofriasborda@gmail.com
    #        password: 123
    #        sender: devellany
    #        from: enzo
    #        to: devellay@dico.me
    #        subject: mail title.
    #        body: <h1>Hello word</h1>
    #        contentType: text/html
    #        attachments: '{"aa":"aaa"}'
    # - uses: actions/checkout@v2
    # - name: Send email
    #   uses: devellany/send-mail@v1.0.2
    #   with:
    #       host: smtp.naver.com
    #       account: ${{ secrets.MAIL_ADDRESS }}
    #       password: ${{ secrets.MAIL_PASSWORD }}
    #       sender: devellany
    #       from: ${{ secrets.MAIL_ADDRESS }}
    #       subject: Github Actions job result
    #       body: file://README.md
    #       attachments: '[{"path":"README.md"}]'
    #       to: enzo_kpo_01@hotmail.com

    # - name: Send email
    #   uses: devellany/send-mailer@v1.0.2
    #   with:
    #       # Optional port (defaults to 465)
    #       port: 465
    #       account: ${{secrets.MAIL_ADDRESS}}
    #       password: ${{secrets.MAIL_PASSWORD}}
    #       sender: devellany
    #       from: ${{secrets.MAIL_ADDRESS}}
    #       to: devellay@dico.me
    #       subject: mail title.
    #       body: your messages.
    #       # Optional content type (defaults to text/plain)
    #       contentType: text/plain
    #       # Optional attachment files (JSON type. require property 'path')
    #       attachments: '[{"path":"README.md"}]'
