name: CI
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
        server_address: smtp.gmail.com
        port: 465
        username: ${{secrets.MAIL_ADDRESS}}
        password: 12345
        subject: Workflow finished
        body: Job completed ${{job.status}}
        to: enzo_kpo_01@hotmail.com
        from: Me 
    # - uses: actions/checkout@v2
    # - name: Send email
    #   uses: devellany/send-mail@v1.0.2
    #   with:
    #       host: smtp.naver.com
    #       account: ${{ secrets.MAIL_ADDRESS }}
    #       password: ${{ secrets.MAIL_PASSWORD }}
    #       sender: devellany
    #       from: ${{ secrets.MAIL_ADDRESS }}
    #       subject: Github Actions job result
    #       body: file://README.md
    #       attachments: '[{"path":"README.md"}]'
    #       to: enzo_kpo_01@hotmail.com

    # - name: Send email
    #   uses: devellany/send-mailer@v1.0.2
    #   with:
    #       # Optional port (defaults to 465)
    #       port: 465
    #       account: ${{secrets.MAIL_ADDRESS}}
    #       password: ${{secrets.MAIL_PASSWORD}}
    #       sender: devellany
    #       from: ${{secrets.MAIL_ADDRESS}}
    #       to: devellay@dico.me
    #       subject: mail title.
    #       body: your messages.
    #       # Optional content type (defaults to text/plain)
    #       contentType: text/plain
    #       # Optional attachment files (JSON type. require property 'path')
    #       attachments: '[{"path":"README.md"}]'
