name: Auto-Approve PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_approve:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GHTOKEN }} # This must be added on the secrets section on GitHub dashboard

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
      - name: Verify PR files
        id: check_changes
        run: python ./.github/workflows/automerge-pr/verify-pr-files.py

      - name: Auto-approve PR
        if: steps.check_changes.outputs.pending == 'false'
        run: |
          gh pr merge ${{ github.event.number }} --auto --merge
