name: Auto-Approve PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: patricksan/email-action@v2
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Auto-approval of PR'
          body: 'The pull request has been auto-approved.'
          to: 'enzofriasborda@gmail.com'
